export const TOOL_IDS = {
    "Alchemist's Supplies": "alchemist",
    "Bagpipes": "bagpipes",
    "Brewer's Supplies": "brewer",
    "Calligrapher's Supplies": "calligrapher",
    "Playing Cards Set": "card",
    "Carpenter's Tools": "carpenter",
    "Cartographer's Tools": "cartographer",
    "Chess Set": "chess",
    "Cobbler's Tools": "cobbler",
    "Cook's Utensils": "cook",
    "Dice Set": "dice",
    "Disguise Kit": "disg",
    "Drum": "drum",
    "Dulcimer": "dulcimer",
    "Flute": "flute",
    "Forgery Kit": "forg",
    "Glassblower's Tools": "glassblower",
    "Herbalism Kit": "herb",
    "Horn": "horn",
    "Jeweler's Tools": "jeweler",
    "Leatherworker's Tools": "leatherworker",
    "Lute": "lute",
    "Lyre": "lyre",
    "Mason's Tools": "mason",
    "Navigator's Tools": "navg",
    "Painter's Supplies": "painter",
    "Pan Flute": "panflute",
    "Poisoner's Kit": "pois",
    "Potter's Tools": "potter",
    "Shawm": "shawm",
    "Smith's Tools": "smith",
    "Thieves' Tools": "thief",
    "Tinker's Tools": "tinker",
    "Viol": "viol",
    "Weaver's Tools": "weaver",
    "Woodcarver's Tools": "woodcarver"
};

export const RULES_IDs = {
    "Inspiration": "inspiration",
    "Carrying Capacity": "carrying capacity",
    "Encumbrance": "encumbrance",
    "Hiding": "hiding",
    "Passive Perception": "passive perception",
    "Falling": "falling",
    "Suffocating": "suffocating",
    "Lightly Obscured": "lightly obscured",
    "Heavily Obscured": "heavily obscured",
    "Bright Light": "bright light",
    "Dim Light": "dim light",
    "Darkness": "darkness",
    "Blindsight": "blindsight",
    "Darkvision": "darkvision",
    "Truesight": "truesight",
    "Surprise": "surprise",
    "Difficult Terrain": "difficult terrain",
    "Size": "size",
    "Grappling": "grappling",
    "Shoving": "shoving",
    "Half Cover": "half cover",
    "Three- Quarters Cover": "three- quarters cover",
    "Total Cover": "total cover",
    "Instant Death": "instant death",
    "Death Saving Throws": "death saving throws",
    "Underwater Combat": "underwater combat",
    "Attunement": "attunement",
    "Telepathy": "telepathy"
};

